# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: taigak.github.io
email: backnum5509atgmail.com
description: 名刺に載せたりするための個人紹介用に作ったページです。それとブログ。<br>© 2017 Taiga Kanehara All rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://taigak.github.io" # the base hostname & protocol for your site
twitter_username: dekai_iwa
github_username:  taigak
facebook_username: Taiga.Kanehara.8.26

# Build settings
markdown: kramdown
